### ISSUE TITLE
QPWGraph hangs when saving configuration

### ISSUE THREAD

**Issue by mbainter** [flathub/org.rncbc.qpwgraph#24] opened 2023-01-09 20:35 UTC
I am running the flatpak on PopOS 22.04, and whenever I try to save the configuration the GUI becomes unresponsive, and no configuration file is saved in the location it suggests -- nor do attempts to save elsewhere work.

**Comment by travier** [comment] 2023-01-10 14:52
I can save configurations on my system. Is your xdg-document-portal installed / functioning properly?

**Comment by kjcole** [comment] 2023-05-26 19:29
I'm having the same issue (I think):

* OS: **Pop! OS 22.04 LTS**
* qpwgraph Version: **0.4.2**
* Using: **Qt 6.4.3, libpipewire 0.3.67 (headers: 0.3.66)**
* Package: **Flatpak**
* Flatpak version: **1.12.7**

When I use `Patchbay` -> `Save as...` the application seems to choose a different location every time despite my explicit choosing of a directory. 

It uses `/run/user/1000/doc/by-app/org.rncbc.qpwgraph/.../filename.qpwgraph` and `~/.xdp-filename-...` where `filename` is what I actually typed and `...` is some random hash in both cases. On next use, it seems to sometimes generate new hashes and forgets where it has previously put stuff.

And it often freezes so that I have to issue a `killall -15 qpwgraph`. Even that seems to not be enough. Usually I end up doing a reboot which may be overkill.

**Expected / preferred behavior**

I would like to use a directory of my choosing, for example `~/patchbays/` and not add any hash to the filenames. And to look in that directory upon subsequent uses of the program.

Upon rebooting, I often get an error dialog 
```
Error - A Pipewire Graph Qt GUI Interface
Could not open patchbay file
/run/user/1000/.../filename.qpwgraph
Sorry
```
![qpwgraph-error](https://github.com/flathub/org.rncbc.qpwgraph/assets/459840/99e1be07-8e33-402e-8af6-bab0a792c9ca)
 
> _Is your xdg-document-portal installed / functioning properly?_

I have no idea. I don't even know what an `xdg-document-portal` is. How would I check if it's installed and if it's "functioning properly"? (A quick look around the 'net suggests that there was a problem with it as recently as Flatpak 1.11...)

 ----
 
 Originally filed as a [rncbc qpwgraph issue](https://gitlab.freedesktop.org/rncbc/qpwgraph/-/issues/72#note_1928729) where it was suggested this was a Flatpak issue.

**Comment by travier** [comment] 2023-05-30 07:15
This is due to how Flatpak portals work. From `$HOME/.var/app/org.rncbc.qpwgraph/config/rncbc.org/qpwgraph.conf`·

```
[Patchbay]
Activated=false
AutoPin=true
Dir=/run/user/1000/doc/cb8c87b9
Exclusive=false
Path=/run/user/1000/doc/cb8c87b9/foo.qpwgraph
RecentFiles=/run/user/1000/doc/cb8c87b9/foo.qpwgraph, /run/user/1000/doc/1f4f2bb5/test.pb
```

This path is randomly generated by the files desktop portal. I likely only changes on reboot thus why we have this only after a reboot and that I can not reproduce it by just closing the app.

I tried giving this app access to the full home dir but that did not help as the files are saved via the portal.

If you save files in `$HOME/.var/app/org.rncbc.qpwgraph/data/bar.qpwgraph` then it should work as this folder is specific to the Flatpak.

**Comment by kjcole** [comment] 2023-05-30 10:15
It appears the problem was a Flatpak permissions problem.  Using **flatseal** and enabling access to **All user files** seems to be working. But it's good to know that saving to `$HOME/.var/app/org.rncbc.qpwgraph/data/....qpwgraph` would also work. That may come in handy for other problems. Thanks.

**Closed** 2023-06-18 09:18 UTC
